### ISSUE TITLE
AI don't detect AI

### ISSUE THREAD

**Issue by ToffelsKater** [rlewicki/AdvancedSightSupport#9]
Hello, just wondering if this is even possible with this plugin?
I have an AI setup like in the documentation, and it works good for detecting a player controlled pawn,
Somehow it can't detect AI controlled pawns, the player and AI classes are the same actually, but it only detects player controlled pawns

**Comment by rlewicki** [comment]
Hi @ToffelsKater! It is of course possible. All you need to do is ensure that both AI use different team ID. Team ID is used to determine the affiliation and to find out whether they should  be friendly or hostile to each other. You can find more info about team ID and how to set it up here: https://rlewicki.tech/advanced-sight-docs/getting-started.html#target-character

Let me know if you need any further help!

**Comment by ToffelsKater** [comment]
Hey i tried that already, Same Team,Different Team. i also checked "Detection by Affiliation"  to detect all and it still wants to detect only my player
the parent class the ai and player uses have AdvancedSightTarget AND AdvancedSightTeam components

**Comment by rlewicki** [comment]
Hmmm that's very strange. Give me a few to run some tests and I'll get back to you in a bit.

**Comment by rlewicki** [comment]
@ToffelsKater I stand corrected, it is indeed not working! And I know exactly why! I have a fix ready for it but it might take Epic a bit to process the files (sometimes they process it within few hours, sometimes even up to a day or two). I will let you know as soon as new version is available on the marketplace!

**Comment by ToffelsKater** [comment]
Much appreciated!

**Comment by rlewicki** [comment]
@ToffelsKater well, I went offline for just a while and just now noticed that Epic has processed the update. If you get latest version from the marketplace now, everything should work! Let me know if everything is alright!

**Comment by ToffelsKater** [comment]
Thank you very much it seems like it works now!
![image](https://github.com/user-attachments/assets/e3b5e7b4-bd75-475f-b25b-249bfba89cad)
